name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out Repo
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v27

      - name: Build & Run Tests
        run: nix develop -c ./do test --release

      - name: Package
        run: nix develop -c ./do package
