name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out Repo
        uses: actions/checkout@v2

      - name: Setup Nix
        uses: cachix/install-nix-action@v27

      - name: Build & Run Tests
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: nix develop -c ./do build test --production
